# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 00:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import viewer.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(max_length=250, verbose_name='Description')),
                ('date', models.DateTimeField(auto_now=True)),
                ('archive', models.FileField(upload_to='albums/', validators=[viewer.validators.validate_zip_extension], verbose_name='Zip file archive')),
                ('cover', models.FileField(blank=True, null=True, upload_to='albums/covers', validators=[viewer.validators.validate_image_extension])),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
